steps:
  - name: "gcr.io/cloud-builders/git"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        git clone https://github.com/antoniomoneo/AIRE---Guardianes-del-Aire app
        cd app
        npm install
        npm run build
        cp -r build ../build

  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t", "us-west1-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:${_VERSION}",
        "-f", "infra/Dockerfile",
        "."
      ]

  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-west1-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:${_VERSION}"
      ]

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run", "deploy", "${_SERVICE}",
        "--region", "${_REGION}",
        "--image", "us-west1-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:${_VERSION}",
        "--platform", "managed",
        "--allow-unauthenticated",
        "--service-account", "${_RUNTIME_SA}",
        "--set-secrets", "GEMINI_API_KEY=GEMINI_API_KEY:latest"
      ]
