name: Deploy app by ref (manual)

on:
  workflow_dispatch:
    inputs:
      app_ref:
        description: "Ref de la app a desplegar (tag/rama/SHA)"
        required: true
        default: "main"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout infra repo
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: aire-469506

      - name: Configure Docker auth for Artifact Registry
        run: gcloud auth configure-docker europe-west1-docker.pkg.dev --quiet

      - name: Clone app repo at requested ref
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          set -euxo pipefail
          rm -rf app
          git clone "https://${GH_PAT}@github.com/antoniomoneo/Social-Media-Planner-aml.git" app
          cd app
          git fetch origin --tags --prune --depth=100
          git checkout --detach "${{ github.event.inputs.app_ref }}"
          echo "APP_COMMIT=$(git rev-parse HEAD)" >> $GITHUB_ENV
          echo "APP_SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          cd -

      - name: Build & Push Docker image
        run: |
          IMAGE="europe-west1-docker.pkg.dev/aire-469506/apps/aire-guardianes-app:${APP_SHORT_SHA}"
          docker build -t "$IMAGE" ./app
          docker push "$IMAGE"
          echo "DEPLOY_IMAGE=$IMAGE" >> $GITHUB_ENV

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy aire-guardianes \
            --image "$DEPLOY_IMAGE" \
            --region europe-west1 \
            --platform managed \
            --allow-unauthenticated
