name: Deploy app by ref (manual)

on:
  workflow_dispatch:
    inputs:
      app_repo:
        description: 'Repo de la app'
        required: true
      app_ref:
        description: 'Ref (rama, tag, commit)'
        required: true
      service_name:
        description: 'Servicio Cloud Run destino'
        required: true
      region:
        description: 'Región'
        required: true
      project_id:
        description: 'ID de proyecto'
        required: true

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout infra repo (this repo)
        uses: actions/checkout@v4

      - name: Clone app repo via PAT
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          set -euxo pipefail
          rm -rf app
          git clone --depth=1 "https://${GH_PAT}@github.com/${{ github.event.inputs.app_repo }}.git" app
          cd app
          git fetch origin ${{ github.event.inputs.app_ref }} --depth=1 || true
          git checkout -q ${{ github.event.inputs.app_ref }} || true
          cd -

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ github.event.inputs.project_id }}

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker us-west1-docker.pkg.dev --quiet

      - name: Build & Push Docker image (Dockerfile en infra/)
        run: |
          set -euxo pipefail
          IMAGE_BASE="${{ github.event.inputs.region }}-docker.pkg.dev/${{ github.event.inputs.project_id }}/apps/aire-guardianes-app"
          TAG1="${IMAGE_BASE}:${{ github.event.inputs.app_ref }}"
          TAG2="${IMAGE_BASE}:${GITHUB_SHA::7}"

          # Dockerfile en infra/, contexto en la raíz del repo (.)
          docker build -f infra/Dockerfile -t "${TAG1}" -t "${TAG2}" .

          docker push "${TAG1}"
          docker push "${TAG2}"
          echo "DEPLOY_IMAGE=${TAG2}" | tee -a $GITHUB_ENV

      - name: Deploy to Cloud Run
        run: |
          set -euxo pipefail
          gcloud run deploy "${{ github.event.inputs.service_name }}" \
            --image "${DEPLOY_IMAGE}" \
            --region "${{ github.event.inputs.region }}" \
            --project "${{ github.event.inputs.project_id }}" \
            --platform managed \
            --allow-unauthenticated \
            --labels "app_repo=${{ github.event.inputs.app_repo }},app_ref=${{ github.event.inputs.app_ref }},commit=${GITHUB_SHA}"
