name: Deploy aire-guardianes → Cloud Run (infra repo)

on:
  push:
    branches: [ "main" ]
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      version:
        description: "Versión (p.ej. v2025.08.28-1). Si se omite, se usa el SHA."
        required: false
        type: string

env:
  PROJECT_ID: aire-470107
  REGION: us-west1
  SERVICE: aire-guardianes
  AR_REPO: aire-guardianes-app
  IMAGE_NAME: aire-guardianes
  RUNTIME_SA: aire-deployer@aire-470107.iam.gserviceaccount.com
  APP_REPO: antoniomoneo/AIRE---Guardianes-del-Aire

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout infra repo (this repo)
        uses: actions/checkout@v4

      - name: Clone app repo via PAT
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          APP_REPO: ${{ env.APP_REPO }}
        run: |
          set -euxo pipefail
          rm -rf app
          git clone --depth=1 "https://${GH_PAT}@github.com/${APP_REPO}.git" app
          cd app
          git fetch origin main --depth=1 || true
          git checkout -q main || true

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev -q

      - name: Compute tags
        id: meta
        shell: bash
        run: |
          if [ -n "${{ github.event.inputs.version }}" ]; then
            TAG="${{ github.event.inputs.version }}"
          elif [[ "${GITHUB_REF:-}" == refs/tags/* ]]; then
            TAG="${GITHUB_REF#refs/tags/}"
          else
            TAG="${GITHUB_SHA}"
          fi
          echo "TAG=$TAG" >> "$GITHUB_OUTPUT"

      - name: "Build and Push image (doble tag: SHA + version)"
        env:
          PROJECT_ID: ${{ env.PROJECT_ID }}
          REGION:     ${{ env.REGION }}
          REPO:       ${{ env.AR_REPO }}
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
          TAG:        ${{ steps.meta.outputs.TAG }}
        run: |
          set -euxo pipefail
          export DOCKER_BUILDKIT=1
          IMAGE_BASE="${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPO}/${IMAGE_NAME}"
          SHA_TAG="${GITHUB_SHA}"
          TAG_NAME="${TAG}"

          # Build (sin --progress y sin --no-cache)
          docker build -f infra/Dockerfile -t "${IMAGE_BASE}:${SHA_TAG}" .

          # Push por SHA
          docker push "${IMAGE_BASE}:${SHA_TAG}"

          # Tag legible (versión) y push
          docker tag "${IMAGE_BASE}:${SHA_TAG}" "${IMAGE_BASE}:${TAG_NAME}"
          docker push "${IMAGE_BASE}:${TAG_NAME}"

      - name: Deploy to Cloud Run
        env:
          PROJECT_ID: ${{ env.PROJECT_ID }}
          REGION:     ${{ env.REGION }}
          SERVICE:    ${{ env.SERVICE }}
          RUNTIME_SA: ${{ env.RUNTIME_SA }}
          REPO:       ${{ env.AR_REPO }}
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
          TAG:        ${{ steps.meta.outputs.TAG }}
        run: |
          set -euxo pipefail
          IMAGE="${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPO}/${IMAGE_NAME}:${TAG}"

          gcloud run deploy "${SERVICE}" \
            --image "${IMAGE}" \
            --region "${REGION}" \
            --service-account "${RUNTIME_SA}" \
            --allow-unauthenticated \
            --ingress all \
            --set-secrets "GEMINI_API_KEY=GEMINI_API_KEY:latest"

      - name: Show Service URL
        run: |
          gcloud run services describe ${{ env.SERVICE }} \
            --region ${{ env.REGION }} \
            --format='value(status.url)'
